# Generated by Django 5.2.7 on 2025-10-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(unique=True)),
                ('published', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(default='BBC', max_length=100)),
            ],
        ),
    ]
