# Generated by Django 5.2.7 on 2025-11-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0002_newsarticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
