# Generated by Django 5.2.7 on 2025-11-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0004_country_region_remove_newsarticle_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
