# Generated by Django 5.2.7 on 2025-11-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0005_newsarticle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
    ]
