# Generated by Django 5.2.7 on 2025-11-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0006_remove_newsarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
